project:
  type: website
  output-dir: docs

website:
  title: "John Hinkle"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - Publications.qmd
      
  
format:
  html:
    theme:
      light: yeti
      dark: [yeti, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

