---
title: "Publications"
---

**Hinkle, J.E.**, Chanton, J.P., Moynihan, M.A., Ruff, S.E. and Teske, A., 2025. Complex bacterial diversity of Guaymas Basin hydrothermal sediments revealed by synthetic long-read sequencing (LoopSeq). *Frontiers in Microbiology*, *15*. <https://doi.org/10.3389/fmicb.2024.1491488>

Ramírez, G.A., Mara, P., Beaudoin, D., Bojanova, D.P., **Hinkle, J.E.**, Kingham, B., Edgcomb, V.P., Morono, Y. and Teske, A.P., 2024. Data report: the DNA event horizon in the Guaymas Basin subsurface biosphere: technical advances and redefined limits in bulk extractions of nucleic acids from deep marine sediments, IODP Expedition 385. *Proceedings of the International Ocean Discovery Program*, *385*. <https://doi.org/10.14379/iodp.proc.385.204.2024>

**Hinkle, J.E.**, Mara, P., Beaudoin, D.J., Edgcomb, V.P. and Teske, A.P., 2023. A PCR-based survey of methane-cycling archaea in methane-soaked subsurface sediments of Guaymas Basin, Gulf of California. *Microorganisms*, *11*(12). [**https://doi.org/10.3390/microorganisms11122956**](https://doi.org/10.3390/microorganisms11122956)
